url: https://epidemos.github.io
#url: https://epidemos.com
#baseurl: /agency-jekyll-theme/
baseurl: /epidemos.github.io/

# Site settings
title: epidemos
email: info@epidemos.com
description: "epidemos - epidemiology in disasters, emergencies, & outbreak settings"


# Team names, titles and social links
people:
- name: Jonathan Polonsky
  pic: 1
  position: Epidemiologist/Lead data scientist
  cv: <a href="/cv/cv_polonsky.pdf" download>
  social:
    # - title: envelope-o
    #   url: mailto:jonathan@epidemos.com
    - title: twitter
      url: http://twitter.com/jonny_polonsky
    - title: linkedin
      url: https://www.linkedin.com/in/jonnypolonsky
    # - title: stack-overflow
    #   url: http://stackoverflow.com/users/1540735/jonny-polonsky
    - title: github
      url: http://github.com/jpolonsky
    - title: pencil
      url: http://communicationinscience.com
    - title: file-text-o
      url: /cv/cv_polonsky.pdf

- name: Xavier de Radiguès
  pic: 2
  position: Epidemiologist/Lead zen master
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/epi_demos
  - title: facebook
    url: https://www.facebook.com/epidem0s
  - title: github
    url: http://github.com/epidemos
  - title: bitbucket 
    url: https://bitbucket.org/epidemos/
  
# Postal address (add as many lines as necessary)
address:
  - line: Quai Charles-Page 37
  - line: Geneva 1205
  - line: Switzerland

# Build settings
markdown: kramdown
permalink: pretty
