url: https://epidemos.github.io
#url: https://epidemos.com
#baseurl: /agency-jekyll-theme/
baseurl: /epidemos.github.io/

# Site settings
title: epidemos
email: info@epidemos.com
description: "epidemos - epidemiology in disasters, emergencies, & outbreak settings"


# Team names, titles and social links
people:
- name: Jonathan Polonsky
  pic: 1
  position: Epidemiologist/Lead data scientist
  social:
    # - title: envelope-o
    #   url: mailto:jonathan@epidemos.com
    - title: file-pdf-o
      url: /cv/cv_polonsky.pdf
    - title: researchgate
      url: https://www.researchgate.net/profile/Jonathan_Polonsky
    - title: linkedin
      url: https://www.linkedin.com/in/jonnypolonsky
    # - title: github
    #   url: http://github.com/jpolonsky
    - title: presentation
      url: http://communicationinscience.com
    - title: twitter
      url: http://twitter.com/jonny_polonsky
    # - title: stack-overflow
    #   url: http://stackoverflow.com/users/1540735/jonny-polonsky
  bio: <p align="justify">Jonathan studied <a href="http://www.ihs.ox.ac.uk/" rel="nofollow">Human Sciences</a> at <a href="http://www.ox.ac.uk/" rel="nofollow">Oxford University</a>, followed by postgraduate training in epidemiology at the <a href="http://www.lshtm.ac.uk/" rel="nofollow">London School of Hygiene and Tropical Medicine</a> (LSHTM). He has been involved in conducting and communicating biomedical research in a variety of posts at LSHTM, the <a href="http://who.int/en/" rel="nofollow">World Health Organization</a> (WHO), <a href="http://www.msf.org/" rel="nofollow">Médecins Sans Frontières</a> (MSF), and <a href="http://epicentre.msf.org/" rel="nofollow">Epicentre</a> (a research department of MSF).</p><p align="justify">Jonathan has extensive experience in humanitarian contexts, where he has focussed on neglected tropical disease epidemiology, assessing mortality and malnutrition trends among displaced populations, rapid health assessments in sudden-onset crises, & outbreak investigation/response. In addition, he advises on research methodology in challenging contexts, reproducible research best practice, effective scientific communication, and local capacity building. He is a proficient programmer in the <a href="https://www.r-project.org/" rel="nofollow">R statistical language</a> and the interactive <a href="http://shiny.rstudio.com/" rel="nofollow">'Shiny'</a> data visualisation & exploration package. Jonathan is a member of the <a href="http://www.ease.org.uk/" rel="nofollow">European Association of Science Editors</a></p>


- name: Xavier de Radiguès
  pic: 2
  position: Epidemiologist/Senior health advisor
  social:
    - title: file-pdf-o
      url: /cv/cv_deradigues.pdf
    - title: researchgate
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/xavier-de-radigu%C3%A8s-20a1b13b
  bio: <p align="justify">Xavier Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. Cu eum dicam feugiat noluisse. Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim.</p><p align="justify">Cu eum dicam feugiat noluisse.Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. Cu eum dicam feugiat noluisse. Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim.</p>


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/epi_demos
  - title: facebook
    url: https://www.facebook.com/epidem0s
  - title: github
    url: http://github.com/epidemos
  - title: bitbucket 
    url: https://bitbucket.org/epidemos/
  
# Postal address (add as many lines as necessary)
address:
  - line: Quai Charles-Page 37
  - line: Geneva 1205
  - line: Switzerland

# Build settings
markdown: kramdown
permalink: pretty
