url: https://epidemos.github.io
#baseurl: /agency-jekyll-theme/
baseurl: /epidemos.com

# Site settings
title: epidemos
email: jonny.polonsky@gmail.com
description: "epidemos - epidemiology in disasters, emergencies, & outbreak settings"


# Team names, titles and social links
people:
- name: Jonny Polonsky
  pic: 1
  position: Epidemiologist/Lead data scientist
  social:
    - title: twitter
      url: http://twitter.com/jonny_polonsky
    - title: linkedin
      url: https://www.linkedin.com/in/jonnypolonsky
    - title: stack-overflow
      url: #
    - title: github
      url: http://github.com/jpolonsky

- name: Xavier de Radiguès
  pic: 2
  position: Epidemiologist/Lead zen master
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Dr. Zoidberg
  pic: 3
  position: Medical doctor/Lead decapodian
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/epi_demos
  - title: facebook
    url: https://www.facebook.com/epidemos
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/r
  - title: bitbucket 
    url: https://bitbucket.org/epidemos/
  - title: github
    url: http://github.com/epidemos

# Postal address (add as many lines as necessary)
address:
  - line: Quai Charles-Page 37
  - line: Geneva 1205
  - line: Switzerland

# Build settings
markdown: kramdown
permalink: pretty
