url: https://epidemos.github.io
#url: https://epidemos.com
#baseurl: /agency-jekyll-theme/
baseurl: /epidemos.github.io/

# Site settings
title: epidemos
email: info@epidemos.com
description: "epidemos - epidemiology in disasters, emergencies, & outbreak settings"


# Team names, titles and social links
people:
- name: Jonathan Polonsky
  pic: 1
  position: Epidemiologist/Lead data scientist
  social:
    # - title: envelope-o
    #   url: mailto:jonathan@epidemos.com
    - title: file-pdf-o
      url: /cv/cv_polonsky.pdf
    - title: researchgate
      url: https://www.researchgate.net/profile/Jonathan_Polonsky
    - title: linkedin
      url: https://www.linkedin.com/in/jonnypolonsky
    - title: github
      url: http://github.com/jpolonsky
    - title: presentation
      url: http://communicationinscience.com
    - title: twitter
      url: http://twitter.com/jonny_polonsky
    # - title: stack-overflow
    #   url: http://stackoverflow.com/users/1540735/jonny-polonsky
  bio: Jonathan received an undergraduate degree in Human Sciences at Oxford University, followed by a postgraduate degree in epidemiology at the London School of Hygiene and Tropical Medicine (LSHTM). He has been involved in conducting and communicating biomedical research in a variety of posts at LSHTM, the World Health Organization (WHO), and Médecins Sans Frontières (MSF). Jonathan is currently employed part-time as an epidemiologist with Epicentre (a research department of MSF), and as Senior Health Advisor to Relief International. Jonathan is a member of the European Association of Science Editors (EASE), and has conducted workshops in scientific communication in a number of countries, including France, Germany, Spain, Morocco, Myanmar, and Senegal.


- name: Xavier de Radiguès
  pic: 2
  position: Epidemiologist/Senior health advisor
  social:
    - title: file-pdf-o
      url: /cv/cv_deradigues.pdf
    - title: linkedin
      url: #
    - title: facebook
      url: #
  bio: Xavier Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. Cu eum dicam feugiat noluisse. Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. Cu eum dicam feugiat noluisse. Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. Cu eum dicam feugiat noluisse. Lorem ipsum dolor sit amet, usu cu alterum nominavi lobortis. At duo novum diceret. Tantas apeirian vix et, usu sanctus postulant inciderint ut, populo diceret necessitatibus in vim. Cu eum dicam feugiat noluisse.


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/epi_demos
  - title: facebook
    url: https://www.facebook.com/epidem0s
  - title: github
    url: http://github.com/epidemos
  - title: bitbucket 
    url: https://bitbucket.org/epidemos/
  
# Postal address (add as many lines as necessary)
address:
  - line: Quai Charles-Page 37
  - line: Geneva 1205
  - line: Switzerland

# Build settings
markdown: kramdown
permalink: pretty
